### ISSUE TITLE
Unicode support is broken in double quoted values

### ISSUE THREAD

**Issue by panzi** [venthur/dotenv-cli#109]
As [described in the Python documentation](https://docs.python.org/3/library/codecs.html#text-encodings) the `unicode_escape` text encoding interprets the bytes as ASCII (or rather ISO-8859-1, I think). Meaning if you write any Unicode characters in a doubled quoted string the result will be the typical "UTF-8 interpreted as ISO-8859-1" encoding error.

Meaning this `.env` file:

```dotenv
FOO=ä
BAR="ä"
BAZ='ä'
```

Is equivalent to this JSON:

```JSON
{ "FOO": "ä", "BAR": "Ã¤", "BAZ": "ä" }
```

The line in question:
https://github.com/venthur/dotenv-cli/blob/78ab62bfc33903eeee59ef483a8b1399c7d6dbd5/dotenv_cli/core.py#L66

The only way to fix this is to implement escape sequence parsing by hand.

**Comment by venthur** [comment]
I can confirm this issue. Very annoying.
