### ISSUE TITLE
Option to prompt for required (but unset) values

### ISSUE THREAD

**Issue by masaeedu** [venthur/dotenv-cli#2]
Hello. Would it be possible to prompt the user for options that are required but missing (either by throwing an error if there is no tty or asking interactively if there is)?

**Comment by venthur** [comment]
Can you elaborate what you mean with required but missing options?

**Comment by masaeedu** [comment]
I mean that instead of having:

```
DB_PASSWORD=
```

just become an empty string in the environment, I also have the option to write:

```
DB_PASSWORD=<required>
```

and if the user hasn't set that as an environment variable or in a `.development` override file, they should get an error (or be interactively prompted for the value of that variable).

**Comment by venthur** [comment]
But a `.env` file is already a shortcut for: 

```bash
$ export DB_PASSWORD=foo
$ your_command
```

So I assume that a `.env` file contains **always** key-values. I might be wrong or I don't understand the concrete use-case. Are you aware of any other `dotenv`-like implementation that supports your feature?

**Comment by masaeedu** [comment]
@venthur Yes, here are some implementations that support this feature:

- https://www.npmjs.com/package/dotenv-safe
- https://hackage.haskell.org/package/dotenv
- https://github.com/vlucas/phpdotenv#requiring-variables-to-be-set
- https://github.com/bkeepers/dotenv#required-keys

**Comment by venthur** [comment]
The repositories you linked to enable required keys only from within the code. I.e. if you use the respective `dotenv` implementation as a library. This `dotenv` (i.e. mine) does not provide any library-like functionality on purpose. I believe the code that is consuming environment variables should not be aware at all about any `.env` files, or **how** the environment variables are provided.
